# Site settings
title: Rajanjamu
email: rajanjamu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Good morning people. Nice to see you all. Lets have some fun.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rajanjamu.githug.io" # the base hostname & protocol for your site
twitter_username: rajanjamu1
github_username:  rajanjamu

# Build settings
markdown: kramdown
